apiVersion: apps/v1
kind: Deployment
metadata:   
  annotations:  
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas" 
  name: go-gdqwkygl
spec:
  replicas: 1 
  template: 
    spec:
      containers:
      - image: quay.io/rhtap_qe/go-gdqwkygl:0e784ceeafd582cac7739a860f11a569e639c9c8@sha256:f5fa0fd22be321fd9f919dce80cdaa7b3a688529a5b059ecdd3211b4b2ec6f7e
        name: container-image  
